### ISSUE TITLE
Error to show the Viewer example

### ISSUE THREAD

**Issue by khoaho** [Autodesk-Forge/forge-boilers.nodejs#1]
Hi,

I have 401 (Unauthorized) error to run [viewer.html](https://github.com/Autodesk-Forge/forge-boilers.nodejs/blob/master/2%20-%20viewer-barebone/viewer.html) with token getting from POST /authentication/v1/authenticate with `scope = data:read`

The 401 error is: GET https://developer.api.autodesk.com/viewingservice/v1/dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6bGVlZnNtcC1mb3JnZS1wZXJzL3Rlc3QuZHdm

**Comment by khoaho** [comment]
I tested the same 401 error with [viewingApp.html](https://github.com/Autodesk-Forge/forge-boilers.nodejs/blob/master/2%20-%20viewer-barebone/viewingApp.html) too. The token in viewingApp.html is replaced with a new 2-legged token.

I even tried multiple scopes `data:create`, `data:read` and `data:write`, but none of them work.

**Comment by leefsmp** [comment]
You also need to use a URN that has been generated with your own credentials otherwise you will get unauthorised error

**Comment by khoaho** [comment]
Thank you. The URN is private, not public as I thought. I think it was public before.

**Comment by leefsmp** [comment]
There is no such thing as a public URN, it is always tied to the set keys that was used to upload/translate/generate the token for viewing
