### ISSUE TITLE
Deprecated in favor of learnforge?

### ISSUE THREAD

**Issue by petrbroz** [Autodesk-Forge/forge-boilers.nodejs#10]
@augustogoncalves, @cyrillef,

I would suggest that we deprecate this repository in favor of https://github.com/Autodesk-Forge/learn.forge.viewmodels, because:

- It's using SDKs that are deprecated (for example, https://github.com/Autodesk-Forge/forge.oauth2-js or https://github.com/Autodesk-Forge/forge.oss-js)
- It includes examples of serving Forge Viewer assets from custom origins which is not allowed by our licensing terms
- I would say that http://learnforge.autodesk.io provides more up-to-date boilerplate projects for Node.js as well as other languages
- In my opinion, some of the boilerplates here are quite heavy
  - For example, the boilerplate for a _3 - viewer+server_ includes 36 npm dependencies, incl. webpack, babel, etc.
  - I believe boilerplate projects should be as lightweight as possible

What do you think?

**Comment by augustogoncalves** [comment]
@petrbroz makes sense, even the live version points to forge-rcdb, so seems deprecated anyway. 

as part of the review process, please adjust the readme to include a deprecated message and add a link to other resources (learnforge, rcdb, etc.)

**Comment by augustogoncalves** [comment]
![image](https://user-images.githubusercontent.com/4291593/61962850-54cded80-af7f-11e9-9f0c-0c34810200cc.png)

changed the description.
