### ISSUE TITLE
Projects 4,5 don't work locally

### ISSUE THREAD

**Issue by SelaOAL** [Autodesk-Forge/forge-boilers.nodejs#2]
I'm trying to run project 5 locally, everything was green when running `npm run build-dev`, but after `npm run dev` and navigating to localhost:3000, I get a very long message that ends with:

>  developerMessage: 'The client_id specified does not have access to the api product',
>      userMessage: '',
>      errorCode: 'AUTH-001',
>      'more info': 'http://developer.api.autodesk.com/documentation/v1/errors/AUTH-001' } }

And nothing has changed in the watcher window.

I have all the APIs in the app ticked on and my id and secret do work in other projects.

And project 4, I see my buckets on the left, but it looks like the download or upload buttons don't do anything and nothing shows up on the main panel which I assume is the viewer.

And I get the following error after a few seconds of pressing the buttons:

> TypeError: First argument must be a string or Buffer
>     at ServerResponse.OutgoingMessage.write (_http_outgoing.js:456:11)
>     at writetop (C:\forge-boilers.nodejs-master\4 - viewer+server+oss\node_modules\express-session\index.js:296:22)
>     at ServerResponse.end (C:\forge-boilers.nodejs-master\4 - viewer+server+oss\node_modules\express-session\index.js:351:16)
>     at C:/forge-boilers.nodejs-master/4 - viewer+server+oss/src/server/api/endpoints/oss.js:166:11
>     at next (native)
>     at step (C:\forge-boilers.nodejs-master\4 - viewer+server+oss\src\server\api\endpoints\oss.js:19:191)
>     at C:\forge-boilers.nodejs-master\4 - viewer+server+oss\src\server\api\endpoints\oss.js:19:361
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> uncaughtException
> TypeError: First argument must be a string or Buffer
>     at ServerResponse.OutgoingMessage.end (_http_outgoing.js:555:11)
>     at writeend (C:\forge-boilers.nodejs-master\4 - viewer+server+oss\node_modules\express-session\index.js:261:22)
>     at Immediate.ontouch (C:\forge-boilers.nodejs-master\4 - viewer+server+oss\node_modules\express-session\index.js:348:11)
>     at runCallback (timers.js:637:20)
>     at tryOnImmediate (timers.js:610:5)
>     at processImmediate [as _immediateCallback] (timers.js:582:5)
> TypeError: First argument must be a string or Buffer
>     at ServerResponse.OutgoingMessage.end (_http_outgoing.js:555:11)
>     at writeend (C:\forge-boilers.nodejs-master\4 - viewer+server+oss\node_modules\express-session\index.js:261:22)
>     at Immediate.ontouch (C:\forge-boilers.nodejs-master\4 - viewer+server+oss\node_modules\express-session\index.js:348:11)
>     at runCallback (timers.js:637:20)
>     at tryOnImmediate (timers.js:610:5)
>     at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by leefsmp** [comment]
I've updated the code fixing some minor errors in the server code, can you try again? This error very much looks like you have an issue with the API keys though ...

**Comment by SelaOAL** [comment]
Project 5 works now.
Thanks.
