### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by ycjcl868** [Autodesk-Forge/forge-boilers.nodejs#4]
![image](https://user-images.githubusercontent.com/13595509/27120643-fdae8e38-5116-11e7-9d03-750831974d60.png)

**Comment by leefsmp** [comment]
That's the expected behaviour, you need to click on "User Data" which will kick off the login process.

**Comment by jpryne** [comment]
I'd say there's an issue here. "viewer-offline.html" in "1 - viewer-offline", for example, refers to:
"viewer-lib/style.css"
There is no folder "viewer-lib" let alone "style.css" (or "three.min.js", "viewer3d.js, etc..)
