### ISSUE TITLE
Local example "viewer-offline.html" is missing resources.

### ISSUE THREAD

**Issue by jpryne** [Autodesk-Forge/forge-boilers.nodejs#5]
"viewer-offline.html" in "1 - viewer-offline", for example, refers to:
"viewer-lib/style.css"
There is no folder "viewer-lib" let alone "style.css" (or "three.min.js", "viewer3d.js, etc..)

**Comment by leefsmp** [comment]
Unfortunately the viewer API is now copyrighted, so I was asked to removed it from that repo since it is under MIT license. You may get a copy of the whole SDK for offline viewing when downloading a translated model from [https://extract.autodesk.io](https://extract.autodesk.io).

**Comment by jpryne** [comment]
Well then shouldn't the entire example be removed from the repo if it is non-functioning?

**Comment by haydenjameslee** [comment]
+1 to removing the example. Just wasted time following the instructions and trying to debug this issue.
