### ISSUE TITLE
Error running 'npm install' in Node.js command line

### ISSUE THREAD

**Issue by Mykita** [Autodesk-Forge/forge-boilers.nodejs#7]
Hi!

I am getting some ERR! as I try to run the install. Is it supposed to look like this, or am I doing something wrong?

`
> C:\Users\tgrim\Downloads\1\1>npm install
> forge-boilers.nodejs@1.0.0 postinstall C:\Users\tgrim\Downloads\1\1
> npm run install-boiler5
> forge-boilers.nodejs@1.0.0 install-boiler5 C:\Users\tgrim\Downloads\1\1
> npm install --prefix ./5\ -\ viewer+server+oss+derivatives
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "viewer+server+oss+derivatives": Tags may not have any characters that encodeURIComponent encodes.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tgrim\AppData\Roaming\npm-cache\_logs\2017-07-26T19_10_35_097Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forge-boilers.nodejs@1.0.0 install-boiler5: `npm install --prefix ./5\ -\ viewer+server+oss+derivatives`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forge-boilers.nodejs@1.0.0 install-boiler5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tgrim\AppData\Roaming\npm-cache\_logs\2017-07-26T19_10_35_341Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forge-boilers.nodejs@1.0.0 postinstall: `npm run install-boiler5`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forge-boilers.nodejs@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tgrim\AppData\Roaming\npm-cache\_logs\2017-07-26T19_10_35_604Z-debug.log`

**Comment by Mulberry0** [comment]
I am also having some difficulties with one of the commands. I am running Terminal on Mac and I am getting this error as i run npm start:

`
> Muls-MacBook-Pro-2:5 muls$ nam start
> Forge-boiler-5@1.0.0 start /Users/muls/Downloads/forge-boilers.nodejs-master/5
> node bin/start.js
Server listening on: 
{ address: '::', family: 'IPv6', port: 3000 }
ENV: undefined
dist/ directory not found, starting compiler ...
Starting compiler NODE_ENV=undefined
Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: Cannot find module './undefined.webpack.config'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at build (/Users/muls/Downloads/forge-boilers.nodejs-master/5/webpack/index.js:42:25)
    at clean.then (/Users/muls/Downloads/forge-boilers.nodejs-master/5/webpack/index.js:61:3)
    at <anonymous> code: 'MODULE_NOT_FOUND' } }  reason:  { Error: Cannot find module './undefined.webpack.config'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at build (/Users/muls/Downloads/forge-boilers.nodejs-master/5/webpack/index.js:42:25)
    at clean.then (/Users/muls/Downloads/forge-boilers.nodejs-master/5/webpack/index.js:61:3)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
Cleaning Dir: /Users/muls/Downloads/forge-boilers.nodejs-master/5/TMP
`

What does it mean that Module Not Found?

**Comment by leefsmp** [comment]
You need to define the required environment variables, NODE_ENV determines which config file will be used:

    > npm install
    > set NODE_ENV=development
    > set FORGE_DEV_CLIENT_ID=<YOUR CLIENT ID FROM DEVELOPER PORTAL>
    > set FORGE_DEV_CLIENT_SECRET=<YOUR CLIENT SECRET>
    > npm start
