### ISSUE TITLE
Boiler Project #5 - Errors getting and creating buckets

### ISSUE THREAD

**Issue by harry-anderson** [Autodesk-Forge/forge-boilers.nodejs#8]
Hi there,

I am trying to run the Boiler Project 5 in development config. 

I have installed dependencies and set my environment variables -webpack builds successfully. 

When loading localhost:3000 I see these errors in chrome console:

![get-error](https://user-images.githubusercontent.com/14777088/29150039-5ba72010-7dbb-11e7-81aa-eb5527102f93.JPG)

Any idea what would be causing this?

**Comment by leefsmp** [comment]
Hard to tell... just put a `console.log(ex)` [there](https://github.com/Autodesk-Forge/forge-boilers.nodejs/blob/master/5%20-%20viewer%2Bserver%2Boss%2Bderivatives/src/server/api/endpoints/oss.js#L42)

**Comment by harry-anderson** [comment]
I fixed the problem,

I had incorrectly set my environment variables to FORGE_CLIENT_ID instead of FORGE_DEV_CLIENT_ID

Once the correct env variables were set the buckets loaded fine.

Thanks for you help @leefsmp
